from __future__ import annotations

import operator
from typing import Annotated, Any, TypedDict

from nakama_kun.ai.models.message import Message
from nakama_kun.ai.models.plan import Plan
from nakama_kun.orchestration.evidence import EvidenceStore
from nakama_kun.orchestration.task_classifier import TaskType
from nakama_kun.orchestration.verification import VerificationReport


class AgentState(TypedDict):
    """The central state maintained throughout the LangGraph agent workflow."""

    # The user's input request/goal
    goal: str

    # The structured plan built by the Planner node
    plan: Plan | None

    # The list of artifacts that must be created for the task to be considered complete
    required_artifacts: list[str]

    # The list of artifacts that have been created so far during the execution phase
    created_artifacts: list[str]

    # Required artifacts that still need to be created before completion.
    missing_artifacts: list[str]

    # Remaining repository-exploration budget before delivery becomes mandatory.
    research_budget_remaining: int

    # True once the executor must stop exploring and create the required outputs.
    delivery_mode: bool

    # Retry memory passed back to the planner after rejections.
    retry_memory: RetryMemory

    # The running log of LLM chat messages (accumulates over node execution)
    messages: Annotated[list[Message], operator.add]

    # Log of tools that were run during the task
    tool_results: Annotated[list[dict[str, Any]], operator.add]

    # Structured workspace verification snapshot produced by the Verifier node.
    # Contains real file contents, command exit codes, and workspace listings —
    # the Reviewer evaluates this instead of raw tool summaries.
    verification_report: VerificationReport | None

    # Structured evidence store containing preserved tool outputs, validations, etc.
    evidence_store: EvidenceStore | None

    # Feedback from the Reviewer node if work needs adjustment
    reviewer_feedback: str | None

    # Retry count to prevent infinite planning/execution loops
    retry_count: int

    # Final synthesized answer for the user
    final_response: str | None

    # Current execution phase status: planning, executing, reviewing, done, failed
    status: str

    # Proposals generated by the Coder Agent
    coder_proposals: list[dict[str, Any]]

    # Decisions and transitions history of all agents
    agent_history: list[dict[str, Any]]

    # Phase 1 Multi-Agent Architecture extensions
    active_agent: str
    agent_outputs: dict[str, Any]
    agent_metrics: dict[str, Any]

    # Target agent routing for rejection feedback (e.g. 'planner' or 'coder')
    reviewer_route: str | None

    # Lightweight task classification used by the Final Response Node to choose
    # between retrieval-focused and metrics-focused response strategies.
    # Set by the Planner node from the goal string via task_classifier.classify_task().
    task_type: TaskType

    # True if the user's goal (specifically retrieval) is satisfied and no more tools are needed.
    goal_satisfied: bool

    # Telemetry captured when early termination is triggered
    early_stop_telemetry: dict[str, Any] | None



class RetryMemory(TypedDict):
    """Stateful memory used to prevent repeated failed strategies across retries."""

    completed_actions: list[str]
    failed_actions: list[str]
    failed_validations: list[str]
    reviewer_feedback: list[str]
    failed_attempt_signatures: list[str]
